### ISSUE TITLE
Ctrl-C kills the rb process

### ISSUE THREAD

**Issue by gaballench** [gaballench/rev-mode#2]
This should stop the execution of the command rather than killing `rb-process`. `julia` from ESS kills the ongoing command input rather than the julia process.

**Comment by etkayapar** [comment]
Hi Gustavo! I've realized that this issue stems from the way`rb` executable parses text input. Currently program chooses to quit if the input was CTRL-C or CTRL-D. Relevant part of the revbayes source code is [here](https://github.com/revbayes/revbayes/blob/ae00cc719f49279c4c831e266fb8d36f482b07db/src/revlanguage/ui/RevClient.cpp#L354)

**Comment by gaballench** [comment]
Thank you @etkayapar! Very interesting finding. I'm closing this issue as this is a feature of `rb`'s binary and not necessarily under control of elisp code.
